.TH touch 1 "DXTouch version 1.5"
.TF touch
.SH NAME
touch - touch file timestamp
.br
.SH SYNOPSIS
.B touch
[options] file...
.br
.SH DESCRIPTION
.B Touch
changes the time/date of last modification for each file argument.
.sp
.B Options:
.sp
.in +4
.ti -4
-d
.br
Specifies the date to assign to each file.
The default is the current system date.
The date must be specified in MMDDYY format.
.sp
Example:
.sp
.ti +4
touch -d061785 myfile
.sp
would change the date on myfile to June 17,
1985.
.sp
.ti -4
-t
.br
Specifies the time to assign to each file.
The default is the current system time.
The time must be specified in 24 HHMM format.
.sp
Example:
.sp
.ti +4
touch -t0945 myfile
.sp
would change the time on myfile to 9:45am.
.sp
.ti +4
touch -t1720 myfile
.sp
would change the time on myfile to 17:20
(5:20pm).
.sp
.ne 5
.ti -4
-w
.br
Specifies what directory to use as the current working
directory.  The default is the current working directory
at the time
.B make
is invoked.  The directory name must immediately follow
the 'w' in the argument list, with no intervening space.
.sp
.ti -4
-?
.br
Outputs the copyright and a summary of the
program.  If this argument is given, no
other arguments may be given.  This option is
not available when running under Microsoft
Windows.
.sp
.in -4
.ne 7
.SH NOTES
When running under MS-DOS, invoking
.B touch
with no command line arguments is considered an
error, and causes the message "no files specified"
to be displayed.  However, if
.B touch
is invoked with no command line arguments when running
under Microsoft Windows, a dialog box is activated from
which the command line arguments can be chosen
interactively.  Once the desired arguments have been
chosen, clicking the 'OK' button continues execution
with the chosen arguements, while clicking the 'Cancel'
button terminates execution.
.SH FILES
None.
.SH BUGS
None known.
.SH ACKNOWLEDGEMENTS
MS-DOS is a registered trademarks of Microsoft Corporation.
Microsoft Windows is a trademark of Microsoft Corporation.
